apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
  labels:
    app: mongodb
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: c2VjcmV0MTIz
  mongo-database: bXVjaHRvZG8=