apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: muchtodo
  labels:
    app: muchtodo-backend
data:
  PORT: "8080"
  ENV: "production"
  MONGO_DB: "muchtodo"
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"